In [3]:
import numpy as np

In [4]:
lista = [1, 2, 3]
lista

[1, 2, 3]

In [5]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Convertendo a lista num array

In [6]:
np.array(lista)

array([1, 2, 3])

In [7]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Criando arrays

### arange

In [8]:
np.arange(0, 12, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Matriz e vetores de zero

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Matriz e vetores de 1

In [11]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Matriz Identidade

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### linspace
* inicio, fim, quantos números na função

In [15]:
np.linspace(1, 10, 2)

array([ 1., 10.])

In [16]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [17]:
np.linspace(1, 10, 8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [18]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Random

### rand

In [21]:
np.random.rand(5)

array([0.25506252, 0.01784722, 0.81997207, 0.69428018, 0.81849816])

In [22]:
np.random.rand(5) * 100

array([22.34723354, 86.16341144, 98.8815698 ,  9.86415438, 12.06480219])

In [24]:
np.random.rand(5, 4) * 100

array([[53.17426617, 82.25872452, 24.28740841, 37.32533717],
       [41.63498219,  4.57112694, 40.2232036 , 40.24109939],
       [89.88547729, 73.55048292,  5.05756461,  6.75494182],
       [43.14285298, 99.19262972, 28.38707311, 74.03808692],
       [20.89612912,  1.84735943, 19.86652972, 41.98826783]])

### randn
* randomicamente selecionados de uma distribuição normal, media 0 e desvio padrão 1

In [26]:
np.random.randn(5)

array([ 0.27918619, -0.7518595 , -0.07155783, -0.73338745,  0.14736205])

### randint

In [27]:
np.random.randint(0, 100, 10)

array([72, 70, 76, 24,  2, 67,  9, 27,  8, 61])

# Atributos e métodos do numpy

### reshape
* Array => Vetor


In [29]:
arr = np.random.rand(25)
arr

array([0.06645511, 0.32480627, 0.10265046, 0.86176493, 0.82592086,
       0.26402017, 0.58964462, 0.05331896, 0.59909683, 0.50426528,
       0.08459215, 0.41618739, 0.06577773, 0.80944808, 0.55916584,
       0.47143024, 0.04602793, 0.08061077, 0.82661461, 0.47870107,
       0.0303276 , 0.53370636, 0.67447774, 0.52911027, 0.2252715 ])

In [31]:
matriz = arr.reshape(5,5)
matriz

array([[0.06645511, 0.32480627, 0.10265046, 0.86176493, 0.82592086],
       [0.26402017, 0.58964462, 0.05331896, 0.59909683, 0.50426528],
       [0.08459215, 0.41618739, 0.06577773, 0.80944808, 0.55916584],
       [0.47143024, 0.04602793, 0.08061077, 0.82661461, 0.47870107],
       [0.0303276 , 0.53370636, 0.67447774, 0.52911027, 0.2252715 ]])

### shape

In [32]:
arr.shape

(25,)

In [33]:
matriz.shape

(5, 5)

### max e min

In [41]:
arr.max()

0.8617649313063581

In [42]:
arr.argmax() # índice

3

In [43]:
arr.min()

0.030327596334836504

In [44]:
arr.argmin() # índice

20