In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 30, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

# index

In [4]:
arr[4]

12

# slice

In [5]:
arr[2:5]

array([ 6,  9, 12])

In [6]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [7]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

# mudar valores

In [8]:
arr2 = np.arange(0,30, 2)

arr2[2:] = 100
arr2

array([  0,   2, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100])

# Matrizes

In [9]:
matrix = np.arange(50).reshape((5,10))
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [13]:
matrix.shape

(5, 10)

### slice

In [11]:
matrix[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [12]:
arr3 = matrix[4:5]
arr3

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [17]:
matrix[1:4, 1:3]

array([[11, 12],
       [21, 22],
       [31, 32]])

# Selecionando matriz através de matriz booleana

In [28]:
bol = matrix >= 30
bol

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [29]:
matrix[bol]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])