In [14]:
import numpy as np

# Exemplo 1

In [25]:
arr = np.array([12.99, 15.99 , 10.99, 5.99, 20.99, 4.99, 7.99, 13.99, 2.99, 6.99, 11.99])
arr

array([12.99, 15.99, 10.99,  5.99, 20.99,  4.99,  7.99, 13.99,  2.99,
        6.99, 11.99])

### Extrair valores menores que 12

In [26]:
bol = arr < 12

In [27]:
bol

array([False, False,  True,  True, False,  True,  True, False,  True,
        True,  True])

In [28]:
arr[bol]

array([10.99,  5.99,  4.99,  7.99,  2.99,  6.99, 11.99])

# Exemplo 2

In [31]:
matrix = np.random.randInt(10, 30, 4)

AttributeError: module 'numpy.random' has no attribute 'randInt'